### ISSUE TITLE
Unable to show the Ranking list of some songs

### ISSUE THREAD

**Issue by AXIS5hacker** [Dyfused/Explode-Kotlin#10]
目前出现如下问题
官谱服和自制服合并以前的自制服曲子排行榜出现无法显示的问题。
(如Flower Dance、Don't Never Around、夜襲、METATRON等曲的排行榜)
![Screenshot_20220918_151433_tech dynami dynamitf](https://user-images.githubusercontent.com/73385895/190890818-1e7ae54c-dd3e-4ec0-a568-18112bef9683.jpg)
![Screenshot_20220918_151811_tech dynami dynamitf](https://user-images.githubusercontent.com/73385895/190890821-16fc7c70-b4a3-4f9b-83c8-b489f173374f.jpg)
该问题可能导致游戏闪退

**Comment by Taskeren** [comment]
先删除过期数据，重新下载。
左下角没有难度，怀疑是 chartId 套用了合并前的格式，需要重新下载修正。

**Comment by AXIS5hacker** [comment]
难度不显示好像是原版Dynamite留下的老问题
而且曲目列表也无显示

重新下载后依然无法显示排行榜

**Comment by Taskeren** [comment]
猪鼻空白把旧服的数据记录也一起导到数据库里了，导致程序找不到对应用户。
已经批量删除旧数据，如果遇到数据丢失的情况及时上报。
